### ISSUE TITLE
dismissPopupBar leaves space at bottom.

### ISSUE THREAD

**Issue by wessoll** [LeoNatan/LNPopupController#434]
When calling `tabBarController!.dismissPopupBar(animated: false, completion: nil)` from a view controller that has the tabbar hidden, a stroke (it seems the safe area) remains which I cannot seem to get rid of (the green area).

![RocketSim Recording - iPhone Xs - 2021-03-02 13 40 33](https://user-images.githubusercontent.com/3873374/109650108-12a65e00-7b5d-11eb-9151-c37dddebb05e.gif)

**Comment by LeoNatan** [comment]
Hello,
Can you please create a demo project that reproduces this?
Thanks

**Comment by wesleyscp** [comment]
> Hello,
> Can you please create a demo project that reproduces this?
> Thanks

I added the same project from the .gif on WeTransfer: https://we.tl/t-QmFaetxwoH

Thanks!

**Comment by LeoNatan** [comment]
Thanks
Please keep it alive and I will take a look soon.

**Comment by wesleyscp** [comment]
> Thanks
> Please keep it alive and I will take a look soon.

Do you need more information @LeoNatan. When would you be able to look into the issue?

**Comment by LeoNatan** [comment]
Sorry, have not had time to take a look yet.

**Comment by LeoNatan** [comment]
Transfer expired

I asked for the link to be alive. Please put the repo on GitHub where it can be easily accessible. Thanks

**Comment by wesleyscp** [comment]
https://we.tl/t-lFjqQOfgPc

**Comment by wesleyscp** [comment]
> Transfer expired
> 
> I asked for the link to be alive. Please put the repo on GitHub where it can be easily accessible. Thanks

It's been over two weeks ago, when will you look into this issue? We'd like to send out a release with the minibar asap, but if this issue isn't solved we're going to have to look into other frameworks. Would be great if this issue got solved.

**Comment by LeoNatan** [comment]
This is an open source I maintain in my spare time; I will look at the issue when I have time to spare. Your tone is not appreciated. You are welcome to submit a pull request if you have ideas how to fix, or use something else if it suits your needs.

**Comment by LeoNatan** [comment]
Reproduced the issue in the example project, investigating.

**Comment by LeoNatan** [comment]
For now, as a workaround, you can disable `shouldExtendPopupBarUnderSafeArea`, and that bar won't appear.

**Comment by LeoNatan** [comment]
Fixed

**Comment by LeoNatan** [comment]
2.10.28

**Comment by wessoll** [comment]
> This is an open source I maintain in my spare time; I will look at the issue when I have time to spare. Your tone is not appreciated. You are welcome to submit a pull request if you have ideas how to fix, or use something else if it suits your needs.

Hey man, ofc, but I suppose its fair enough to let people know when and if you will look into it. I don't mind paying for your services to get this issue resolved.

Back to the matter, I can confirm the safe area bar is removed when calling dismiss. Thax! However, when setting the popupbar to hidden, the safe area bar is still present. Setting `shouldExtendPopupBarUnderSafeArea` to false actually will leave a gap between the bottom and popupbar. 

Thax lemme know!

**Comment by iDevelopper** [comment]
@wessoll ,

@LeoNatan replied:

> This is an open source I maintain in my spare time; I will look at the issue when I have time to spare. Your tone is not appreciated. You are welcome to submit a pull request if you have ideas how to fix, or use something else if it suits your needs.

Your tone is definitely unbearable!

**Comment by LeoNatan** [comment]
Part of working on this project in my free time is that I cannot say when I will have free time to work on it. This is the best I can do. Again, if you are unhappy with my performance, feel free to use another framework. As far as I know, this is still the most feature rich, most maintained framework that implements this functionality. I may not be up to date. If you find another, feel free to use it.
