### ISSUE TITLE
LNPopupBar label alignment issues

### ISSUE THREAD

**Issue by jyounus** [LeoNatan/LNPopupController#69]
Hey there,

For some weird reasons, I'm having alignment issues with the text. I've uploaded a screenshot here:

<img src=http://abload.de/img/issuektrru.png />

Here's the code that I'm using:

```
LNPopupBar.appearance().titleTextAttributes = [NSForegroundColorAttributeName : UIColor.whiteColor()]
            LNPopupBar.appearance().subtitleTextAttributes = [NSForegroundColorAttributeName : UIColor.whiteColor()]
            LNPopupBar.appearance().barStyle = UIBarStyle.Black
            LNPopupBar.appearance().tintColor = UIColor.whiteColor()

....

let nc: BaseNC = ...
                //let vc = nc.childViewControllers.first as! QuestionsVC
                nc.popupItem.title = "Complete your profile!"
                nc.popupItem.subtitle = "15/96 questions left"
                nc.popupItem.progress = 0.33

                (nc.childViewControllers.first as! QuestionsVC).appTabs = self.tabBarController

                self.tabBarController?.popupContentView.popupCloseButton?.hidden = true
                self.tabBarController?.presentPopupBarWithContentViewController(nc, openPopup: true, animated: true, completion: nil)

```

The above is just debug code, I'm trying to get this working before I clean it up. Any help would be appreciated.

**Comment by jyounus** [comment]
@LeoNatan I figured out that increasing the title and subtitle to be extra long (so that the text starts animating) causes the labels to be positioned properly. Here's a screenshot: 

<img src=http://abload.de/img/simulatorscreenshot141hur5.png />

```
nc.popupItem.title = "Complete your profile! sdkjf kjashda kjshdfkj askdj faksjd faks dfkjasdhkfjahskdjfhaskd fkasjdfk asdkfjashdkjf aksdfhkjas dfksad"
nc.popupItem.subtitle = "15/96 questions left q9ewru 9w8 riuhwe iebrqwv bvnsbdaf,mdag8 32g2b3be bvdjgs ajdhbans d"
```


Any ideas how to fix this for short text that doesn't need to animate?

**Comment by LeoNatan** [comment]
Could be a bug with the lib I use for scrolling labels. Haven't had time to investigate yet.

**Comment by jyounus** [comment]
Okay, I'll fork and try out an updated version of the MarqueeLabel lib and will report back if I have any luck.

**Comment by LeoNatan** [comment]
Great, thanks. Submit a pull request of it is fixed.

**Comment by jyounus** [comment]
Unfortunately that didn't fix it. :(

**Comment by shilei365** [comment]
How can I change the background color of Popbar in Swift?  I wrote with `self.popupBar?.barTintColor = UIColor.blueColor()`
but `self.popupBar` is always nil.

I tried with 
`LNPopupBar.appearance().backgroundColor = UIColor.blueColor()`
still doesn't work.

**Comment by LeoNatan** [comment]
@shilei365 The popup bar is nil because it is only created during presentation. It is best to use Appearance API:

`LNPopupBar.appearance().barTintColor = UIColor.blueColor()`

**Comment by shilei365** [comment]
@LeoNatan  It works! Thx a lot :)
other 2 qestions: 
1: How can I set the height of PopupBar?
2, How can I disable presenting of the popupContentView? It means, the PopupViewController doesn't show after I've clicked on the popupbar?

**Comment by LeoNatan** [comment]
Height is constant.
I don't understand 2.

**Comment by LeoNatan** [comment]
Also, please don't hijack this issue. Check closed issues for your questions - they have all been answered before.

**Comment by LeoNatan** [comment]
Please test with new 2.0 branch. I cannot reproduce this.
